### ISSUE TITLE
Wikipedia 公式无法显示

### ISSUE THREAD

**Issue by chenjinloong** [xiaoyang-liu-cs/workers-proxy#41]
请问如何能优化Wikipedia里的公式啊？这个项目很好能很好访问Wikipedia等外网，图片什么的都还可以及时显示出来，就是公式总是加载失败

**Comment by xiaoyang-liu-cs** [comment]
测试了一下 Lagrange multiplier:
![](https://wikimedia.org/api/rest_v1/media/math/render/svg/9d499e2e56de16a9a6b2d7df453aad58fa7050dc)
https://wikimedia.org/api/rest_v1/media/math/render/svg/9d499e2e56de16a9a6b2d7df453aad58fa7050dc

**Comment by chenjinloong** [comment]
非常感谢！只是我的办公网络使用该方法仍行不通反而图片也加载不出来。

不过受你启发，将 'wikimedia.org': '$custom_domain' 这一语句结合你项目中ciphncdn的使用
变换为 '//wikimedia.org': '//wikimedia.org.workers.dev', // replace this with your other deployment 可以完美解决低网速下公式显示问题。

**Comment by netptop** [comment]
试试我的siteproxy， 不用配置， 直接访问youtube/twitter/google和维基百科

https://github.com/netptop/siteproxy
